name: Build and Push Container Image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    environment: CI
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Quay Container Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: docker.io/${{ github.repository }}:latest
